### ISSUE TITLE
Horizon crashes after unexpected TransactionResultCode

### ISSUE THREAD

**Issue by thejollyrogers** [stellar/horizon#25] opened 2015-04-28 20:01 UTC
Sent a payment transaction with USD credits to an account that did not have a trust line for the currency/issuer pair (it also happens to be the same account as the sender).

Actor crashed!
XDR::EnumValueError: Unknown Stellar::TransactionResultCode member: -2
	/Users/andrewrogers/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/xdr-0.0.1/lib/xdr/enum.rb:21:in `read'
	org/jruby/RubyKernel.java:1886:in `tap'
	/Users/andrewrogers/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/xdr-0.0.1/lib/xdr/enum.rb:20:in `read'
	/Users/andrewrogers/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/xdr-0.0.1/lib/xdr/union.rb:37:in `read'
	/Users/andrewrogers/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/xdr-0.0.1/lib/xdr/struct.rb:18:in `read'
	org/jruby/RubyHash.java:1341:in `each'
	/Users/andrewrogers/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/xdr-0.0.1/lib/xdr/struct.rb:17:in `read'
	org/jruby/RubyKernel.java:1886:in `tap'
	/Users/andrewrogers/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/xdr-0.0.1/lib/xdr/struct.rb:16:in `read'
	/Users/andrewrogers/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/xdr-0.0.1/lib/xdr/struct.rb:18:in `read'
	org/jruby/RubyHash.java:1341:in `each'
	/Users/andrewrogers/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/xdr-0.0.1/lib/xdr/struct.rb:17:in `read'
	org/jruby/RubyKernel.java:1886:in `tap'
	/Users/andrewrogers/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/xdr-0.0.1/lib/xdr/struct.rb:16:in `read'
	/Users/andrewrogers/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/xdr-0.0.1/lib/xdr/concerns/converts_to_xdr.rb:55:in `from_xdr'
	/Users/andrewrogers/Code/stellar/horizon/app/models/hayashi/transaction.rb:26:in `result_pair'
	/Users/andrewrogers/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/memoist-0.11.0/lib/memoist.rb:147:in `result_pair'
	/Users/andrewrogers/Code/stellar/horizon/app/models/hayashi/transaction.rb:12:in `result'
	/Users/andrewrogers/Code/stellar/horizon/app/models/hayashi/transaction.rb:49:in `fee_paid'
	/Users/andrewrogers/Code/stellar/horizon/app/jobs/history/ledger_importer_job.rb:35:in `perform'
	org/jruby/RubyArray.java:1613:in `each'
	/Users/andrewrogers/Code/stellar/horizon/app/jobs/history/ledger_importer_job.rb:34:in `perform'
	/Users/andrewrogers/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
	/Users/andrewrogers/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'
	/Users/andrewrogers/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
	/Users/andrewrogers/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/activerecord-4.1.9/lib/active_record/transactions.rb:208:in `transaction'
	/Users/andrewrogers/Code/stellar/horizon/app/jobs/history/ledger_importer_job.rb:19:in `perform'
	/Users/andrewrogers/Code/stellar/horizon/app/jobs/application_job.rb:12:in `with_db'
	/Users/andrewrogers/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:294:in `with_connection'
	/Users/andrewrogers/Code/stellar/horizon/app/jobs/application_job.rb:12:in `with_db'
	/Users/andrewrogers/Code/stellar/horizon/app/jobs/history/ledger_importer_job.rb:16:in `perform'
	/Users/andrewrogers/Code/stellar/horizon/lib/instrumentation.rb:62:in `perform_with_instrumentation'
	org/jruby/RubyProc.java:271:in `call'
	/Users/andrewrogers/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/metriks-0.9.9.7/lib/metriks/timer.rb:51:in `time'
	/Users/andrewrogers/Code/stellar/horizon/lib/instrumentation.rb:61:in `perform_with_instrumentation'
	org/jruby/RubyKernel.java:1958:in `public_send'
	/Users/andrewrogers/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
	/Users/andrewrogers/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
	/Users/andrewrogers/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `invoke'
	/Users/andrewrogers/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `task'
	/Users/andrewrogers/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `task'
	/Users/andrewrogers/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `initialize'
	/Users/andrewrogers/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `create'

**Comment by nullstyle** [comment] 2015-05-08 19:52
Duplicate of #29

**Closed by nullstyle** 2015-05-08 19:52 UTC
Labels: bug
